#!/bin/sh /etc/rc.common
# Install as /etc/init.d/hobocams-agent
START=99
USE_PROCD=1

start_service() {
    [ -f /etc/hobocams-agent.conf ] && . /etc/hobocams-agent.conf

    procd_open_instance
    procd_set_param command /usr/bin/hobocams-agent.sh
    procd_set_param env HOBOCAMS_ROLE="$HOBOCAMS_ROLE" HOBOCAMS_SERVER_URL="$HOBOCAMS_SERVER_URL" HOBOCAMS_API_TOKEN="$HOBOCAMS_API_TOKEN"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
